### ISSUE TITLE
Error when touch back button in  mini app on android in new version super-app-showcase use "@callstack/repack": "5.0.0-rc.1"

### ISSUE THREAD

**Issue by doiya46** [callstack/super-app-showcase#110]
## Environment

I try on both Ubuntu and MacOS

## Description

Error when press Back button on android.

Step to reproduce:

1. pnpm start
2. pnpm run:host:android
3. Touch Services in bottom nav tabs and touch shoping.
4. Press back button and it throw error 

## Reproducible Demo

![Image](https://github.com/user-attachments/assets/13e03aba-eaae-4702-a5d7-3f440a9fbcfd)

**Comment by jbroma** [comment]
Closing since this should be resolved by #111

**Comment by jbroma** [comment]
was related to this issue in RNScreens:

https://github.com/software-mansion/react-native-screens/issues/2491
