### ISSUE TITLE
Hot reloading doesn't work in mini app

### ISSUE THREAD

**Issue by ArekChr** [callstack/super-app-showcase#22]
## Description

While testing the app, I encountered an issue with hot reloading in mini app when the host server is started.

@andrewworld Do you know the reason for this limitation?

## Reproducible Demo

1. run `yarn start:host`
2. navigate to services
3. navigate to one of mini app
4. make some changes to the selected mini app

**Comment by jbroma** [comment]
It's currently not possible to perform hot-module replacement of the mini-app embedded into the host-app. Two dev servers would need to communicate with each other and it's a [very complex problem](https://github.com/callstack/repack/issues/174#issuecomment-1182773662)

**Comment by chakravarthi-bb** [comment]
if there is no HMR, what's the suggested way to just run mini apps??

**Comment by jbroma** [comment]
Hi @chakravarthi-bb 

To mitigate the issue with HMR, you can run the `dashboard` mini-app in standalone mode. You can do that by running:
```sh
yarn start:standalone:dashboard // starts dev-server for dashboard mini-app in standalone mode
```

and then run

```sh
yarn run:dashboard:ios
// or
yarn run:dashboard:android
```

Only `dashboard` mini-app includes android & ios directories needed to run the app in standalone mode. You could add them to the rest of the mini-apps as well and have the same experience.

**Comment by trancongdung12** [comment]
Hi @jbroma in auth package can hot reload ?
