### ISSUE TITLE
How can I build an .apk from the host app?

### ISSUE THREAD

**Issue by abhay-keyvalue** [callstack/super-app-showcase#34]
I tryied to build an .apk using assembleRelease in the host app but it crashes when I open in my android device.
On simulator, dev works fine

**Comment by jbroma** [comment]
Hi @abhay-keyvalue, thanks for trying out our template. 

Could please provide me with more details (ideally some `adb logcat` logs) so we can help you solve the issues?

Out of the box, I've noticed that the build for android fails because of:
```> SigningConfig "release" is missing required property "storeFile".```
This is expected as we didn't upload the storefile for the release variant. You can modify `packages/host/android/app/build.gradle` to use `SigningConfig.debug` for the prod-ready apk.

Following this change, the app builds fine for me and displays `Failed to load AuthProvider` which is also kind of expected as we haven't provided the changes necessary to accomodate prod-ready catalog-server that will resolve the requests for federated modules (but we are actively working on that and will show that soon!).

**Comment by akunal1** [comment]
I am also facing same kind of issue with release  build apk. 
Here are the steps : 

1. opened Android folder of host app in android studio 
2. created a release apk.
3. Installed that on a physical device
4. when I am opening it I am getting an error on the screen "Failed to Load Auth Provider". 

I believe when I am building the app it is not including other independent app's bundle into the host app. 
Could you please help me here with the correct steps ?. @jbroma  

Thanks in Advance 🙏🏼

**Comment by Thangtn93** [comment]
I plan to use this example for a new project but example not configured to be deployed in App Stores is big problem
Is there another way for this?

**Comment by akunal1** [comment]
I tried deploying  a release signed bundle in s3-Bucket and tried accessing that from host app . But it said that the bundle is invalid. I must be doing something wrong but have no clues .. 

 ```
const resolveURL = Federated.createURLResolver({
    containers: {
      MiniApp: 'www.link-to-bundle/filename',
    },
  });
```

**Comment by Thangtn93** [comment]
Can I create a local environment for these packages?
<img width="1301" alt="image" src="https://github.com/callstack/super-app-showcase/assets/21117391/d8bd1ea2-14bc-4585-bb07-153fc1ec718c">

**Comment by jbroma** [comment]
> Can I create a local environment for these packages? <img alt="image" width="1301" src="https://user-images.githubusercontent.com/21117391/242317015-d8bd1ea2-14bc-4585-bb07-153fc1ec718c.png">

Could you please clarify what you mean and what you are trying to achieve?

If you would like to serve these packages locally, then all you have to do is just run `yarn start` from the root of the monorepo - this will launch 6 development servers (5 for mini-apps and 1 for host) that will serve all of these packages and they will be available for the host app to consume.

**Comment by Thangtn93** [comment]
> > Can I create a local environment for these packages? <img alt="image" width="1301" src="https://user-images.githubusercontent.com/21117391/242317015-d8bd1ea2-14bc-4585-bb07-153fc1ec718c.png">
> 
> Could you please clarify what you mean and what you are trying to achieve?
> 
> If you would like to serve these packages locally, then all you have to do is just run `yarn start` from the root of the monorepo - this will launch 6 development servers (5 for mini-apps and 1 for host) that will serve all of these packages and they will be available for the host app to consume.
sorry i'm having the same problem as you  [Failed to load AuthProvider ] I don't want to upload bundle auth to S3. I'm looking for a way to load offline bundle

**Comment by Thangtn93** [comment]
> > > Can I create a local environment for these packages? <img alt="image" width="1301" src="https://user-images.githubusercontent.com/21117391/242317015-d8bd1ea2-14bc-4585-bb07-153fc1ec718c.png">
> > 
> > 
> > Could you please clarify what you mean and what you are trying to achieve?
> > If you would like to serve these packages locally, then all you have to do is just run `yarn start` from the root of the monorepo - this will launch 6 development servers (5 for mini-apps and 1 for host) that will serve all of these packages and they will be available for the host app to consume.
> > @jbroma j
 sorry i'm having the same problem as you  [Failed to load AuthProvider ] I don't want to upload bundle auth to S3. I'm looking for a way to load offline bundle

**Comment by jbroma** [comment]
@Thangtn93 I'm afraid at this moment it's not possible to include bundle to be consumed offline like that. I'll will look into it when I get the chance. The only other workaround that comes to my mind is to include the auth package at build time by simplying importing the components needed from the `auth` package.
