### ISSUE TITLE
Error to compile

### ISSUE THREAD

**Issue by DiegoAPG** [callstack/super-app-showcase#48]
## Ask your Question

When I run project in shell aplication, I get this error. Help me

<img width="357" alt="image" src="https://github.com/callstack/super-app-showcase/assets/29066401/54d5d041-3479-4889-93ea-ae14605e21bf">

**Comment by jbroma** [comment]
Hi @DiegoAPG,

I've updated `shell` app, should be running fine now. 

Please remember to start the correct dev servers for it to work:
```sh
yarn start:standalone:shell    # starts dev server for shell
yarn start                     # starts all other dev servers (host will fail because port is taken by shell dev server, and that's fine)
```

then you can run:
```sh
yarn run:shell:android
yarn adbreverse
```

Ideally, please run adbreverse before the shell app builds but after the emulator starts
```

**Comment by jbroma** [comment]
Closing this one as the answer was provided and this issue has been stale for quite some time
