### ISSUE TITLE
Error: ENOENT: no such file or directory, open '/supper-app-showcase/code-signing.pem

### ISSUE THREAD

**Issue by tranvuluan** [callstack/super-app-showcase#52]
This bug occur when I run "yarn run:host:android" after run "yarn start" successfully

**Comment by L-Shiva-Kumar** [comment]
I got the same error when following the same exact steps.

**Comment by jbroma** [comment]
Hi @tranvuluan and @L-Shiva-Kumar,

As we wanted to show production setup in our super-app-showcase, we've recently added some features that are useful for production but not necessarily needed for development. The `code-signing.pem` is used for signing the release version of the super-app-showcase that we have available, and it was added to `.gitignore` for security reasons. 

Here's what you can do about it:
1. Generate your own key using this [gist](https://gist.github.com/ygotthilf/baa58da5c3dd1f69fae9)
2. Rename your private key to `code-signing.pem` and place it in the root of the repository
3. Change the public keys to your public key in the following places:
- for Android: `packages/host/android/app/src/main/res/values/strings.xml`
- for iOS: `packages/host/ios/host/Info.plist`

If you don't want to use code-signing you can always disable it like this:

```diff
diff --git a/packages/host/index.js b/packages/host/index.js
index ea242fc..2452698 100644
--- a/packages/host/index.js
+++ b/packages/host/index.js
@@ -44,7 +44,7 @@ ScriptManager.shared.addResolver(async (scriptId, caller) => {
     query: {
       platform: Platform.OS, // only needed in development
     },
-    verifyScriptSignature: 'strict',
+    verifyScriptSignature: 'off',
   };
 });
```
