### ISSUE TITLE
[ScriptManager] Failed while resolving script locator

### ISSUE THREAD

**Issue by nhoxx** [callstack/super-app-showcase#53]
## Ask your Question
I clone the source and run `yarn run:host:android `--> show error
 [ScriptManager] Failed while resolving script locator: {"caller": undefined, "scriptId": "auth"} {"originalError": [TypeError: Network request failed]} 
<img width="795" alt="image" src="https://github.com/callstack/repack/assets/48126274/76b76919-1905-483e-b666-12fe766bc0df">
Please help me!
Thanks

**Comment by thymikee** [comment]
Did you run `yarn start` first?

**Comment by nhoxx** [comment]
@thymikee  I have run `yarn start`, but not working.
<img width="1400" alt="image" src="https://github.com/callstack/super-app-showcase/assets/48126274/0568a320-29cd-4093-8578-2c07c76b1e27">
<img width="1365" alt="image" src="https://github.com/callstack/super-app-showcase/assets/48126274/18c0472d-4093-47d4-9c6c-696e0c6fda99">

**Comment by nhoxx** [comment]
@thymikee All my steps:
```
yarn
yarn start
yarn adbreverse
yarn run:host:android
```
Show error 
<img width="942" alt="Screenshot 2023-07-12 at 16 23 44" src="https://github.com/callstack/super-app-showcase/assets/48126274/d2d545ed-c1c1-4c26-a340-c17ed76b5903">

**Comment by jbroma** [comment]
hey @nhoxx,

This is a connectivity problem between android emulator and your dev server

`yarn adbreverse` will do nothing unless the emulator is running, try running it after the emulator has started.

**Comment by nhoxx** [comment]
Hi @jbroma @thymikee  thanks for helping me. I will double-check to see if I missed any steps.

**Comment by nhoxx** [comment]
@jbroma I have stuck when building.  `http://localhost:9003auth.container.bundle` not working, it looks like the auth module is having problems. I tried to solve it many times, but not working.
I used this example `https://github.com/callstack/repack-examples`. It working fine.

**Comment by duyanhv** [comment]
> @jbroma I have stuck when building. `http://localhost:9003auth.container.bundle` not working, it looks like the auth module is having problems. I tried to solve it many times, but not working.
> So I used this example https://github.com/callstack/repack-examples .It working fine.

same, i ran "yarn concurrently -P "yarn start:catalog" "yarn start:auth"" to see what's wrong with auth, it got something to do with repack not bundling correctly, i checked the generated/ios folder there's only: node_modules_react-native-async-storage_async-storage_src_index_ts.chunk.bundle not vendors-node_modules_react-native-async-storage_async-storage_src_index_ts.chunk.bundle.
`Error: ENOENT: no such file or directory, open '/Users/superapp/super-app-showcase/packages/auth/build/generated/ios/vendors-node_modules_react-native-async-storage_async-storage_src_index_ts.chunk.bundle'`

after changing the name to vendors-node_modules_react-native-async-storage_async-storage_src_index_ts.chunk.bundle. i got another error.
`Error: ENOENT: no such file or directory, open '/Users/superapp/super-app-showcase/packages/auth/build/generated/ios/vendors-node_modules_pmmmwh_react-refresh-webpack-plugin_lib_runtime_RefreshUtils_js.chunk.bundle'`
i think the error might be in the repack configuration.

**Comment by nhoxx** [comment]
Hi @duyanhv,
You can see this example: https://github.com/callstack/repack-examples. I tried and working fine.

**Comment by duyanhv** [comment]
for anyone who's still searching for the answer: 
command the line `verifyScriptSignature: 'strict'` in /host/index.js
command all new Repack.plugins.CodeSigningPlugin in webpack.config.mjs

**Comment by trancongdung12** [comment]
@duyanhv thanks bro. it's work find with me

**Comment by trancongdung12** [comment]
@nhoxx Can you give me step run ios pls?

**Comment by nhoxx** [comment]
@trancongdung12 what problems do you have during the ios build process?

**Comment by trancongdung12** [comment]
@nhoxx https://github.com/callstack/super-app-showcase/issues/54 this is my issue.

**Comment by nhoxx** [comment]
> @nhoxx #54 this is my issue.

Did you run  `yarn pods` ?

**Comment by trancongdung12** [comment]
@nhoxx I try yarn pods but it still has an error. 
error: Unable to load contents of file list: '/Target Support Files/Pods-host/Pods-host-resources-Debug-input-files.xcfilelist' (in target 'host' from project 'host')

**Comment by mahendramahi** [comment]
This is adb connectivity problem
So use adb reverse command when it come and reload app with all port's number which is using for your host and mini modules.
Like:-  
`adb reverse tcp:3000 tcp:3000 && adb reverse tcp:8081 tcp:8081 && adb reverse tcp:9000 tcp:9000 && adb reverse tcp:9001 tcp:9001 && adb reverse tcp:9002 tcp:9002 && adb reverse tcp:9003 tcp:9003`
