### ISSUE TITLE
Failed to build iOS project

### ISSUE THREAD

**Issue by trancongdung12** [callstack/super-app-showcase#54]
Error when run this project: 
1. yarn start
2. yarn run:host:ios

Help me to fix this issue when run IOS. 

![Screen Shot 2023-07-19 at 10 53 57](https://github.com/callstack/super-app-showcase/assets/55046284/b0a96b86-4c32-4d13-a02d-d38d89974759)

**Comment by jbroma** [comment]
Hey @trancongdung12,

I believe you forgot to install pods which you can do by running
```sh
cd packages/host
yarn pods
```

if it fails to install the pods, you can delete the `Podfile.lock` file inside of the `ios` directory.
```sh
rm packages/host/ios/Podfile.lock
```

and after that try running installing the pods again.
