### ISSUE TITLE
Unhandled error [ScriptManager] Failed to load script: [ScriptDownloadFailure]

### ISSUE THREAD

**Issue by toandn96** [callstack/super-app-showcase#56]
## Environment

System:
    OS: macOS 13.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 159.66 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 19.9.0 - /usr/local/bin/node
    Yarn: 3.2.1 - /usr/local/bin/yarn
    npm: 9.8.0 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.12.1 - /Users/GVL02253/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.3 AI-223.8836.35.2231.10406996
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.20 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.8 => 0.71.8 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Description

* When I run the command **run:host:ios** app running and then I get the error like below: 

**Error: ENOENT: no such file or directory, open '/workspace/showcase/super-app-showcase/packages/auth/build/generated/ios/vendors-node_modules_pmmmwh_react-refresh-webpack-plugin_lib_runtime_RefreshUtils_js.chunk.bundle'**

ℹ [07:50:14.804Z][DevServer] Server listening at http://[::1]:9003 
⇢ [07:50:21.548Z][LoggerPlugin] Compiling ios: 3% setup (watch run) 
⇢ [07:50:23.113Z][LoggerPlugin] Compiling ios: 26% building (3/10 entries 13/13 dependencies 3/12 modules) 
⇢ [07:50:25.207Z][LoggerPlugin] Compiling ios: 26% building (3/10 entries 390/500 dependencies 41/135 modules) 
⇢ [07:50:27.102Z][LoggerPlugin] Compiling ios: 31% building (4/10 entries 758/900 dependencies 92/286 modules) 
⇢ [07:50:29.595Z][LoggerPlugin] Compiling ios: 31% building (4/10 entries 1286/1400 dependencies 120/393 modules) 
⇢ [07:50:32.327Z][LoggerPlugin] Compiling ios: 31% building (4/10 entries 1600/1712 dependencies 146/426 modules) 
⇢ [07:50:33.846Z][LoggerPlugin] Compiling ios: 32% building (4/10 entries 2030/2100 dependencies 214/553 modules) 
⇢ [07:50:35.068Z][LoggerPlugin] Compiling ios: 31% building (4/10 entries 2454/2477 dependencies 288/593 modules) 
⇢ [07:50:36.421Z][LoggerPlugin] Compiling ios: 31% building (4/10 entries 2468/2500 dependencies 288/597 modules) 
⇢ [07:50:39.711Z][LoggerPlugin] Compiling ios: 32% building (4/10 entries 2611/3000 dependencies 313/597 modules) 
⇢ [07:50:41.414Z][LoggerPlugin] Compiling ios: 37% building (5/10 entries 3571/3595 dependencies 519/683 modules) 
node:internal/event_target:1036
  process.nextTick(() => { throw err; });
                           ^

Error: ENOENT: no such file or directory, open '/Users/GVL02253/workspace/showcase/super-app-showcase/packages/auth/build/generated/ios/vendors-node_modules_pmmmwh_react-refresh-webpack-plugin_lib_runtime_RefreshUtils_js.chunk.bundle'
Emitted 'error' event on Compiler instance at:
    at Worker.<anonymous> (/Users/GVL02253/workspace/showcase/super-app-showcase/packages/auth/node_modules/@callstack/repack/dist/webpack/Compiler.js:110:14)
    at Worker.emit (node:events:513:28)
    at MessagePort.<anonymous> (node:internal/worker:247:53)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:761:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)

![simulator_screenshot_BB586A4F-515C-4F91-BFA3-DE4D869469EF](https://github.com/callstack/super-app-showcase/assets/40200541/1ee4ffc9-5f57-4735-af95-c175d86b221f)

## Reproducible Demo

- Clone source(main branch).
- Install dependencies for all apps: yarn
- Install pods where applicable : yarn pods
- yarn start:host
- yarn start:auth
- yarn start:catalog
- yarn run:host:ios

Thanks in advance!

**Comment by toandn96** [comment]
**Error: ENOENT: no such file or directory, open '.../packages/auth/build/generated/ios/auth.container.bundle'
Emitted 'error' event on Compiler instance at:
at Worker. (/.../packages/auth/node_modules/@callstack/repack/dist/webpack/Compiler.js:110:14)
at Worker.emit (node:events:513:28)
at MessagePort. (node:internal/worker:247:53)
at [nodejs.internal.kHybridDispatch] (node:internal/event_target:761:20)
at exports.emitMessage (node:internal/per_context/messageport:23:28)**

=> Because miss file code-signing.pem: 
 Run: `openssl genrsa -out jwtRSA256-private.pem 2048` to fix it.

=> Because file code-signing.pem is missing:
=>  Run: `openssl genrsa -out code-signing.pem 2048` to fix it.
Reference : https://techdocs.akamai.com/iot-token-access-control/docs/generate-jwt-rsa-keys

**Comment by jbroma** [comment]
Hi @toandn96,

I've recently updated the repository where the `CodeSigningPlugin` is disabled in development, please check whether this resolves your issue

**Comment by toandn96** [comment]
> Hi @toandn96,
> 
> I've recently updated the repository where the `CodeSigningPlugin` is disabled in development, please check whether this resolves your issue

Hi @jbroma , 

Thanks for your update. It works well for me.
