### ISSUE TITLE
How to handle a case where mini apps are in separate repositories

### ISSUE THREAD

**Issue by krzysztofzaluski** [callstack/super-app-showcase#62]
In this example we have sample mini apps inside packages folder in one repository. Can we handle a case when we have one host app in one repository and other mini app packages comes from separate repositories?

We have "federatedDependencies" in host/package.json where we can provide an URL - so it's only about to change this URL to specific mini app repository URL and that's all?

**Comment by krzysztofzaluski** [comment]
ok, now I just noticed that there is an example with remote repository with "news" package, sorry for that, closing the question ;)

**Comment by thymikee** [comment]
Glad you found it. If you see anything that could be easier to discover, please feel free to contribute to the docs :)
