### ISSUE TITLE
No bundle URL present

### ISSUE THREAD

**Issue by saravanan6137** [callstack/super-app-showcase#65]
## Environment

[catalog] [CatalogServer] Server listening at port 3000 
[shopping] ℹ [03:54:34.254Z][DevServer] Server listening at http://[::1]:9001 
[dashboard] ℹ [03:54:34.269Z][DevServer] Server listening at http://[::1]:9002 
[host] ℹ [03:54:34.470Z][DevServer] Server listening at http://[::1]:8082 
[booking] ℹ [03:54:34.494Z][DevServer] Server listening at http://[::1]:9000 
[auth] ℹ [03:54:34.650Z][DevServer] Server listening at http://[::1]:9003

## Description

Even through I followed the steps,
1. yarn from root directory.
2. yarn pods from root directory.
3. changed host app "start" command to this -> "start": "react-native webpack-start --port=8082" since 8081 is already used by some other app (mac app)
4. Then from root directory package.json I ran -> "run:host:ios": "yarn workspace host run ios --port=8089 --simulator='iPhone 14 Pro Max'"
5. Build is successful and simulator launches but I get error in simulator
No bundle url present and I see the dev-server which are running are not responding to the app I ran.

All the dev server are running and iOS build also successful

**Comment by jbroma** [comment]
Hey @saravanan6137,

I think you also need to provide `--port 8082` to the `react-native ios` command in the host app, please check that and let me know whether this resolved your issue.

**Comment by saravanan6137** [comment]
Hi @jbroma 
Thanks for the reply. 
yes I tried that also. 
"run:host:ios": "yarn workspace host run ios --port=8082 --simulator='iPhone 14 Pro Max'"

still same issue. if possible can give the steps you followed to run this template or any solution you aware of?
if I run android, the app just gets stuck on the launch screen.
Thanks!

**Comment by saravanan6137** [comment]
Hi jakub,
Thanks for your reply.

Yes I tried like you said just now where I see some improvement (getting
first response from host app).
But still the error remains the same. Please check the screenshots of how I
set up the template.
[image: Screenshot 2023-09-27 at 6.07.19 PM.png]
[image: Screenshot 2023-09-27 at 6.07.37 PM.png]
[image: Screenshot 2023-09-27 at 6.06.05 PM.png]

**Comment by saravanan6137** [comment]
<img width="1057" alt="Screenshot 2023-09-27 at 6 10 21 PM" src="https://github.com/callstack/super-app-showcase/assets/68968235/4b715de9-020d-483c-b837-9cec2a6d655e">
<img width="1165" alt="Screenshot 2023-09-27 at 6 10 53 PM" src="https://github.com/callstack/super-app-showcase/assets/68968235/81881e77-e736-4d8a-a372-fe8d744f681a">
<img width="785" alt="Screenshot 2023-09-27 at 6 11 03 PM" src="https://github.com/callstack/super-app-showcase/assets/68968235/1adf3b37-a2be-4c77-a552-b0cfab171554">

Guys please checkout my setup screenshots

**Comment by jbroma** [comment]
All looks good to me and it should work, try rebuilding the ios app

**Comment by saravanan6137** [comment]
Please let me know the steps I followed are correct.
1. clone the project
2. Run yarn from the root directory.
3. Run yarn pods from the root directory.
4. Go to host app -> package.json -> change like this
"ios": "react-native run-ios --port 8082",
"start": "react-native webpack-start --port=8082"
5. Go to main package.json -> change like this
"run:host:ios": "yarn workspace host run ios --port=8082
--simulator='iPhone 14 Pro Max'",

6. Run yarn start
7. Run "run:host:ios" script.

**Comment by jbroma** [comment]
For ios these steps look correct, I will try to run this on my copy and get back to you

**Comment by saravanan6137** [comment]
Thanks.

**Comment by jbroma** [comment]
I've verified that the app runs correctly on my setup with this changed port. I think you can also try few more things:

- Open `localhost:8082` and verify you get a page with `React Native packager is running`
- Inside the iOS simulator, press `CMD + D` and go to `Configure Bundler` and enter `localhost` for address and `8082` for port
- Try using different port than `8082`

From my POV, this looks like a networking issue and I'm not sure I will be able to assist you with that

**Comment by saravanan6137** [comment]
Thanks! Works now.
