### ISSUE TITLE
Property 'HMRClient' doesn't exist

### ISSUE THREAD

**Issue by HardiBavariya** [callstack/super-app-showcase#83]
## Environment

 Windows: 11
 "@callstack/repack": "^3.7.0"
 Platform: Android
 "react-native": "0.71.8"

## Description

I have followed all steps for Windows system but after running on emulator getting following error:

![Screenshot_20240222_143736](https://github.com/callstack/super-app-showcase/assets/160839885/86f80e0a-4038-4317-909b-345a1e9417e9)

Can anyone help me to fix this issue.

**Comment by jbroma** [comment]
Closing this one as it's already tracked inside of https://github.com/callstack/repack/issues/501
