### ISSUE TITLE
Error integrating redux-toolkit: Unhandled JS Exception

### ISSUE THREAD

**Issue by aw-capgemini** [callstack/super-app-showcase#90]
## Description

I encountered an error while integrating redux-toolkit with the super-app-showcase. The error message is:

`Unhandled JS Exception: Cannot read property 'increment' of undefined
TypeError: Cannot read property 'increment' of undefined
    at ./features/counter/counterSlice.ts`

![Simulator Screenshot - iPhone SE (3rd generation) - 2024-05-28 at 14 05 08](https://github.com/callstack/super-app-showcase/assets/161552403/5d831ff9-b83f-4a96-b367-5b8a8b55a438)

This occurs when trying to use the increment action from the counter slice. The same code works fine in a normal React Native app but fails in the super-app-showcase app.

**Steps to Reproduce:**

Set up redux-toolkit in the project.
Define a counter slice with increment action.
Attempt to dispatch the increment action in a component.

**Expected Behavior:**
The increment action should be dispatched correctly without errors.

**Actual Behavior:**
The application crashes with the error mentioned above.

## Reproducible Demo

https://github.com/aw-capgemini/super-app-showcase/tree/redux-toolkit

**Comment by jbroma** [comment]
Hey, have you checked this? https://github.com/callstack/repack/issues/500#issuecomment-1991677970

this is 99% a resolution issue that was already solved once before. I can see that the demo is using Re.Pack 3.4.0, so all of the steps from the issue need to be applied in order to get this to work.

**Comment by aw-capgemini** [comment]
Hi @jbroma,

Thank you for your response.

To ensure that the resolution issue is fully addressed, do I need to apply all of those steps only on the host or across all modules?

Best regards,
Arjay
