### ISSUE TITLE
Request help in local setup

### ISSUE THREAD

**Issue by Sujay-shetty** [callstack/super-app-showcase#98]
## Ask your Question
Hi Team,

Thank you for creating nice application for reference with federation way of building app.

I'm trying to setup in local but not able to build locally and run in android device. below are some of the errors(Note followed Readme document setup, did pnpm install before executing below commands)
1. If run with command `pnpm start`
    
![image](https://github.com/user-attachments/assets/e98c24f4-bc01-4fae-81a3-42a4bf3c2b79)

2. If run with command `pnpm run:host:android` or `pnpm run:shell:android` is giving multiple errors, is some thing missing in setup ?
    
![image](https://github.com/user-attachments/assets/8abca25d-5184-4091-997c-fe6fba274071)

I'm new to react-native and re.pack
Please let me know if I'm missing any steps?

Thanks,
Sujay

**Comment by thymikee** [comment]
Jakub is on sick leave currently, he’ll come back to you hopefully in a few days

**Comment by Sujay-shetty** [comment]
@jbroma or @thymikee or anyone can you help to build the application?
